# Generated by Django 4.1.7 on 2023-03-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_contact_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='img',
            new_name='image',
        ),
    ]
